"""GRAVITAS data models — events, entities, and intelligence primitives."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class EventSource(Enum):
    """Where did this event come from?"""
    FILE = "file"
    API = "api"
    NETWORK = "network"
    OMNIPENTESTX = "omnipentestx"
    SYSTEM = "system"
    MANUAL = "manual"
    EXTERNAL = "external"


class EventSeverity(Enum):
    """How serious is this event?"""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"
    DEBUG = "debug"

    @staticmethod
    def from_string(s: str) -> EventSeverity:
        mapping = {
            "critical": EventSeverity.CRITICAL,
            "high": EventSeverity.HIGH,
            "medium": EventSeverity.MEDIUM,
            "low": EventSeverity.LOW,
            "info": EventSeverity.INFO,
            "debug": EventSeverity.DEBUG,
        }
        return mapping.get(s.lower(), EventSeverity.INFO)


@dataclass
class RawEvent:
    """A raw data event ingested from any source.

    This is the universal data primitive for GRAVITAS.
    Every piece of intelligence starts as a RawEvent.
    """
    source: EventSource
    source_id: str
    event_type: str
    severity: EventSeverity = EventSeverity.INFO
    data: Dict[str, Any] = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    tags: List[str] = field(default_factory=list)
    correlation_id: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "source": self.source.value,
            "source_id": self.source_id,
            "event_type": self.event_type,
            "severity": self.severity.value,
            "data": self.data,
            "timestamp": self.timestamp,
            "tags": self.tags,
            "correlation_id": self.correlation_id,
        }


@dataclass
class ProcessedEvent:
    """A processed, enriched event ready for inference."""
    raw: RawEvent
    normalized_data: Dict[str, Any] = field(default_factory=dict)
    entities: List[str] = field(default_factory=list)
    confidence: float = 1.0
    enrichment: Dict[str, Any] = field(default_factory=dict)
    processed_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())


@dataclass
class IntelligenceEntity:
    """An entity discovered in the intelligence graph."""
    id: str
    type: str  # ip, domain, user, hash, vulnerability, etc.
    name: str
    properties: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    first_seen: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    last_seen: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    tags: List[str] = field(default_factory=list)


@dataclass
class Prediction:
    """A prediction generated by the inference engine."""
    id: str = ""
    target: str = ""
    prediction_type: str = ""  # attack, compromise, scan, etc.
    probability: float = 0.0
    time_horizon: str = ""  # immediate, short_term, medium_term, long_term
    affected_entities: List[str] = field(default_factory=list)
    suggested_actions: List[str] = field(default_factory=list)
    confidence: float = 0.0
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
